import pickle
import numpy as np
from matplotlib import pylab as plt
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten, BatchNormalization
from keras.layers import Conv2D, MaxPooling2D
from keras.utils import to_categorical
from keras.preprocessing.image import ImageDataGenerator

import keras.backend as K

import psutil
x_data = np.zeros((0,32,32,3))
y_data = np.zeros((0,1))
learning_rate = 0.001
decay = 0
for i in range(1,6):
    raw_data = pickle.load(open('cifar-10-python/data_batch_' + str(i),'rb'),encoding='bytes')
    x_data = np.append(x_data, np.transpose(np.reshape(raw_data[b'data'],[-1,3,32,32]),[0,2,3,1]), axis=0)
    y_data = np.append(y_data, np.array(raw_data[b'labels']))

raw_data = pickle.load(open('cifar-10-python/test_batch','rb'),encoding='bytes')
x_test = np.transpose(np.reshape(raw_data[b'data'],[-1,3,32,32]),[0,2,3,1])
y_test = np.array(raw_data[b'labels'])



def construct_model():
    model = Sequential()
    model.add(Conv2D(32, (3, 3), padding='same',
                 input_shape=[32,32,3]))
    model.add(Activation('relu'))
    model.add(Conv2D(32, (3, 3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))

    model.add(Conv2D(64, (3, 3), padding='same'))
    model.add(Activation('relu'))
    model.add(Conv2D(64, (3, 3)))
    model.add(Activation('relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.25))

    model.add(Flatten())
    model.add(Dense(512))
    model.add(BatchNormalization())
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(10))
    model.add(Activation('softmax'))

    opt = keras.optimizers.Adam(learning_rate=learning_rate, decay=decay)
    # opt = keras.optimizers.SGD(learning_rate=learning_rate, decay=decay)

    # Let's train the model using RMSprop
    model.compile(loss='categorical_crossentropy',
                       optimizer=opt,
                       metrics=['accuracy'])

    return model


model = construct_model()
model.summary()

data_augmentation=True
if not data_augmentation:
    print('Not using data augmentation.')
    model.fit(x_data,y_data,batch_size=32,epochs=200,validation_split=0.1)
else:
    print('Using real-time data augmentation.')
    # This will do preprocessing and realtime data augmentation:
    datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        zca_epsilon=1e-06,  # epsilon for ZCA whitening
        rotation_range=0,  # randomly rotate images in the range (degrees, 0 to 180)
        # randomly shift images horizontally (fraction of total width)
        width_shift_range=0.1,
        # randomly shift images vertically (fraction of total height)
        height_shift_range=0.1,
        shear_range=0.,  # set range for random shear
        zoom_range=0.,  # set range for random zoom
        channel_shift_range=0.,  # set range for random channel shifts
        # set mode for filling points outside the input boundaries
        fill_mode='nearest',
        cval=0.,  # value used for fill_mode = "constant"
        horizontal_flip=True,  # randomly flip images
        vertical_flip=False,  # randomly flip images
        # set rescaling factor (applied before any other transformation)
        rescale=None,
        # set function that will be applied on each input
        preprocessing_function=None,
        # image data format, either "channels_first" or "channels_last"
        data_format=None,
        validation_split=0.1)

    # Compute quantities required for feature-wise normalization
    # (std, mean, and principal components if ZCA whitening is applied).
    datagen.fit(x_data)

    # Fit the model on the batches generated by datagen.flow().
    model.fit_generator(datagen.flow(x_data, y_data,
                                     batch_size=32),
                        epochs=200,
                        validation_data=(x_test, y_test),
                        workers=4)


